### ISSUE TITLE
Initialize new memory arrays with const array

### ISSUE THREAD

**Issue by hajduakos** [SRI-CSL/solidity#101]
Memory arrays are now set to default value only if the size is a compile-time constant. However, we could use SMT const arrays for the general case just as we use it for initializing storage arrays in the constructor. This will make the analysis more precise. E.g.: `ArraysMemWarning.sol`

**Comment by hajduakos** [comment]
Done in db97d5f

Test cases: `ArraysMemDynamic.sol` and `ArraysMemWarning.sol`. In the latter case a warning is given becuse default value is not yet supported for reference types.

**Comment by dddejan** [comment]
```solidity
pragma solidity ^0.5.0;

contract C {
    function test() public pure {
        int[] memory a;
        assert(a.length == 0);
    }
}
```

Currently gives

```
solc-verify.py Test.sol  --show-warnings
Test.sol:5:9: solc-verify warning: Unhandled default value, verification might fail
C::test: ERROR
 - Test.sol:6:9: Assertion might not hold.
C::[implicit_constructor]: OK
Errors were found by the verifier.
```

Doesn't seem like the default allocation is done here.

**Comment by hajduakos** [comment]
Yes, that was missing. Default allocation was only done for `new` expressions. In ac65a2c
it is also done for uninitialized memory arrays. Not yet working for uninitialized memory structs, but I created a new issue for that #102
