### ISSUE TITLE
Support getter arguments

### ISSUE THREAD

**Issue by beillahi** [SRI-CSL/solidity#112]
It seems during the translation of the specification, the aliasing does not work for maps
(cc @michael-emmi)
```
$ cat test5.sol && echo ---- && solc-verify.py test5.sol 
pragma solidity ^0.5.0;

contract test2 {

    mapping(address => uint) public t;

}

contract test  {

    test2 t2;
    address a;

    /**
        @notice precondition t2.t(a) == 0
    */
    function f() public ;
}
----
Error while running verifier, details:
[TRACE] Using prover: /usr/bin/z3
Parsing /tmp/tmpn7em8za8/test5.sol.bpl
/tmp/tmpn7em8za8/test5.sol.bpl(36,141): Error: invalid argument types ([address_t]int and int) to binary operator ==
1 type checking errors detected in /tmp/tmpn7em8za8/test5.sol.bpl
```

**Comment by hajduakos** [comment]
I think the issue here is caused by the getter argument (`a` in `t2.t(a)`). As far as I remember, we did not implement getter arguments. I will check.

**Comment by hajduakos** [comment]
Previously we reported a meaningful error ("getter arguments not supported"), but then I fiddled around a bit to support getters in specs, and now we just seem to ignore the arguments which causes an error in the translation.

**Comment by beillahi** [comment]
Yes, that's right, it works for elementary types but not maps

**Comment by hajduakos** [comment]
What kind of arrays/mappings do you have? As long as they map to primitive types (even if they are multidimensional), it seems easy to solve. But if structs are involved, it seems to get complicated: https://solidity.readthedocs.io/en/v0.5.12/contracts.html#getter-functions, for example check out the `contract Complex` example: the struct is actually split up to a tuple.

**Comment by beillahi** [comment]
Not as complicated as in the complex example. In our case, the arrays and maps involve only primitive types and no structs are necessary

**Comment by hajduakos** [comment]
Done in 06eac49278b9b71aeda5cfc3294e95f5359489c8 for mappings/arrays, possibly nested/multidimensional, but no structs. Check out test cases `test/solc-verify/basic/GetterArgs.sol` and `test/solc-verify/specs/GetterArgsInSpec.sol`

**Comment by beillahi** [comment]
Yes, it works now for the example. Thanks
