### ISSUE TITLE
Event neither specified, nor emitted

### ISSUE THREAD

**Issue by hajduakos** [SRI-CSL/solidity#141]
This example passes, but should fail because `f` should emit`changed` as it changes `data`.
```solidity
contract C {
    mapping(int=>int) data;
    /// @notice tracks-changes-in data
    event changed();
    function f() public {
        data[0] = 1;
    }
}
```
Te problem is that we loop through all the declared `emits` for a function and add the event specs corresponding to those events. However, this way if the developer neither declares nor emits an event, the variable can still be changed. We should also loop through all the variables modified by the function and add the corresponding specs to detect such situations. If possible, it would be good to reuse `AssignHelper` for collecting variables because there are many tricky cases for assignments. (It's not enough to simply look for variables on LHS, e.g., `x = y++`).

**Comment by dddejan** [comment]
Should be fixed, close if it's OK.
