### ISSUE TITLE
Postcondition of function with function call not verifiable

### ISSUE THREAD

**Issue by zhao-nan** [SRI-CSL/solidity#165]
## Description
    pragma solidity >=0.5.0 <0.6.0;
    contract Test {
      int res;

      /// @notice postcondition res == x + 1
      function callInc(int x) public returns (int) {
          res = inc(x);
      }

      /// @notice postcondition res == x + 1
      function inc(int x) public returns (int) {
          res = x+1;
      }
    }

In the above contract, both function contracts should be verifiable. However, solc-verify reports that the first postcondition might not hold.

    Test::callInc: ERROR
     - Test.sol:6:5: Postcondition 'res == x + 1' might not hold at end of function.

## Environment

- Compiler version: 0.5.17-develop.2020.6.23+commit.04e0b152.Linux.g++
- Operating system: Ubuntu 18.04

## Semi-Related question

is it possible to refer to a function's return value? If so, how? In the above, I actually do not want a global `res` variable, but I could not find another way to express this.

**Comment by dddejan** [comment]
Function inc doesn't return anything, the way you wrote the contract both functions write into a state variable but always return zero.

**Comment by dddejan** [comment]
To refer to the return value you need to name the return value 'returns (int res)'.

**Comment by dddejan** [comment]
The following contract verifies fine

```solidity
contract Test {
  /// @notice postcondition res == x + 1
  function callInc(int x) public returns (int res) {
      res = inc(x);
  }

  /// @notice postcondition res == x + 1
  function inc(int x) public returns (int res) {
      res = x+1;
  }
}
```
