### ISSUE TITLE
Enum definition not found internal exception

### ISSUE THREAD

**Issue by nelaturuk** [SRI-CSL/solidity#166]
pragma solidity >=0.5.0;

contract Test {
    enum B { A }

    struct AA {
        B s;
    }

    AA private _aa;

    function test() public view {
        B b = _aa.s;
    }
}

======= Converting to Boogie IVL =======

======= ./solci-verify-experiments/tests/test.sol =======
solc-verify internal exception: Enum definition not found
Details:
/solidity/libsolidity/boogie/ASTBoogieExpressionConverter.cpp(1381): Throw in function virtual bool dev::solidity::ASTBoogieExpressionConverter::visit(const dev::solidity::MemberAccess&)
Dynamic exception type: boost::exception_detail::clone_impl<langutil::InternalCompilerError>
std::exception::what: Enum definition not found
[dev::tag_comment*] = Enum definition not found

**Comment by dddejan** [comment]
Thanks for reporting. Should be fixed. @nelaturuk please check and close if it works.

**Comment by nelaturuk** [comment]
Thank you. The fix works.
