### ISSUE TITLE
undeclared identifier: __verifier_idx_uint error with --arithmetic mod option

### ISSUE THREAD

**Issue by nelaturuk** [SRI-CSL/solidity#168]
```solidity 
pragma solidity >=0.5.0;

/// @notice invariant __verifier_sum_uint(items[__verifier_idx_uint]) >= total
contract C {
    uint total;
    uint[] items;

    function add(uint item) public {
        items.push(item);
        total += item;
    }
}
```

Command: ```solc-verify.py test.sol --arithmetic mod```

![image](https://user-images.githubusercontent.com/3939682/107814352-c4612480-6d3f-11eb-88f9-49185e68c998.png)

**Comment by hajduakos** [comment]
Hi @nelaturuk,

Can you try `/// @notice invariant __verifier_sum_uint(items) >= total`? If the array contains integers `__verifier_idx_uint` is not needed. It is only required if your array/mapping contains structs, and you want to pick some field of the struct, see [example](https://github.com/SRI-CSL/solidity/blob/0.5/test/solc-verify/examples/SumOverStructMember.sol).

**Comment by nelaturuk** [comment]
That works. Thank you.
