### ISSUE TITLE
solc-verify: UNKNOWN_PROCESS_ERROR when running examples

### ISSUE THREAD

**Issue by thanhtoantnt** [SRI-CSL/solidity#173]
## Description
When I run `solc-verify.py test/solc-verify/examples/Annotations.sol` the results are 
`C::add_to_x: UNKNOWN_PROCESS_ERROR`
`C::add: UNKNOWN_PROCESS_ERROR`
`C::[implicit_constructor]: UNKNOWN_PROCESS_ERROR`
`C::[receive_ether_selfdestruct]: UNKNOWN_PROCESS_ERROR`.

I follow the instructions to install `solc-verify` with no problems. Other examples have the same `UNKNOWN_PROCESS_ERROR` results.

**Comment by thanhtoantnt** [comment]
Closed since I resolved the issue

**Comment by stefanandy** [comment]
How did you solve the error?
