### ISSUE TITLE
Optimize encoding of library functions 

### ISSUE THREAD

**Issue by dddejan** [SRI-CSL/solidity#25]
I see in the translation that the library multiplication is translated into

```
mul#18(__this: address_t, __msg_sender: address_t, __msg_value: int, self#5: address_struct_stor_s#3, x#7: int)
```

My understanding of Solidity is that there is no need for __this and other special members. By solidity docs "t can only access state variables of the calling contract if they are explicitly supplied".

_Originally posted by @dddejan in https://github.com/SRI-CSL/solidity/issues/14#issuecomment-499636452_

**Comment by hajduakos** [comment]
I removed `this` in bfb22adddab21146134e66729261cac42aa134b2, but `msg.sender` and `msg.value` are needed, see `issues/Issue025.sol`.

**Comment by hajduakos** [comment]
@dddejan please check and close
