### ISSUE TITLE
Error: more than one declaration of variable name: __this

### ISSUE THREAD

**Issue by dddejan** [SRI-CSL/solidity#29]
Running on 

```solidity
contract C {
    function f() pure public {
        uint super = 3;
        uint this = 4;
    }
}
``` 

Results in

```
./solc-verify.py test/libsolidity/syntaxTests/nameAndTypeResolution/shadowsBuiltin/this_super.sol --output .
Error while running verifier, details:
Parsing ./this_super.sol.bpl
./this_super.sol.bpl(17,125): Error: more than one declaration of variable name: __this
1 name resolution errors detected in ./this_super.sol.bpl
```

**Comment by hajduakos** [comment]
Fixed it in 11b8439f9a2b90f00bb7d11f71c3709ee09ab1b6, also extended the example with functions and structures having conflicting names. Seems like the compiler also checks for magic vars, and then just compares strings: https://github.com/ethereum/solidity/blob/e78500a1994a8dec7f328d4ad8764e79c80b2faf/libsolidity/codegen/ir/IRGeneratorForStatements.cpp#L781
