### ISSUE TITLE
Build failure due to incomplete type

### ISSUE THREAD

**Issue by zhao-nan** [SRI-CSL/solidity#86]
Building (as described in SOLC-VERIFY-README.md) fails with the following error message:
```
[ 53%] Building CXX object libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o
In file included from /home/jonas/programs/solidity/libsolidity/formal/CHC.cpp:21:0:
/home/jonas/programs/solidity/libsolidity/formal/Z3CHCInterface.h:56:17: error: field ‘m_solver’ has incomplete type ‘z3::fixedpoint’
  z3::fixedpoint m_solver;
                 ^~~~~~~~
In file included from /home/jonas/programs/solidity/libsolidity/formal/Z3Interface.h:22:0,
                 from /home/jonas/programs/solidity/libsolidity/formal/Z3CHCInterface.h:25,
                 from /home/jonas/programs/solidity/libsolidity/formal/CHC.cpp:21:
/usr/include/z3++.h:65:11: note: forward declaration of ‘class z3::fixedpoint’
     class fixedpoint;
           ^~~~~~~~~~
libsolidity/CMakeFiles/solidity.dir/build.make:1070: recipe for target 'libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o' failed
make[2]: *** [libsolidity/CMakeFiles/solidity.dir/formal/CHC.cpp.o] Error 1
CMakeFiles/Makefile2:389: recipe for target 'libsolidity/CMakeFiles/solidity.dir/all' failed
make[1]: *** [libsolidity/CMakeFiles/solidity.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
```

Could you give any tips on why this happens? Is a specific version of z3 needed?
Best regards and greetings from Karlsruhe,
Jonas

**Comment by dddejan** [comment]
Related to #61 

Thanks for reporting. 

This is an issue with the upstream solidity compiler which has support for some analysis using SMT solvers. They might require a recent version of the Z3 to use the horn solver (CHC) from Z3.
In their [cmake](https://github.com/SRI-CSL/solidity/blob/6c977281f6cf02e144486ce210903de895c4e661/libsolidity/CMakeLists.txt#L129-L136) setup they require at least Z3 4.6.0 but I have a feeling a newer version is needed.

Which version of Z3 are you using?

If you have some time, maybe you can try to compile the upstream from https://github.com/ethereum/solidity and report there if it doesn't work.

**Comment by hajduakos** [comment]
Hey Jonas! This is because the compiler has some built in smt checker which relies on Z3 libraries but your system probably has some incompatible version. Try adding `-DUSE_Z3=Off` to the `cmake` command. If you have the CVC4 binaries as described in our readme, our tool will detect it and should work with it.

**Comment by zhao-nan** [comment]
I'm using z3 version 4.8.5 which should be recent enough. Turning z3 off in cmake worked, though (although cmake incorrectly reports that cvc4 is not installed).
I reported the issue upstream as you suggested.
Thanks!
