### ISSUE TITLE
Conditional with different data locations

### ISSUE THREAD

**Issue by hajduakos** [SRI-CSL/solidity#92]
We cannot handle if a conditional has different memory locations for the true/false expression.
```solidity
pragma solidity >=0.5.0;
contract Issue092 {
    struct S {
        int x;
    }
    S s1;

    function f(bool b) public {
        s1.x = 1;
        S memory sm = S(2);

        sm = b ? s1 : sm;
        s1 = b ? sm : s1;

        assert(!b || s1.x == 1);
        assert(!b || sm.x == 1);
        assert(b || sm.x == 2);
        assert(b || s1.x == 1);
    }
}
```

solc-verify produces a Boogie program with incompatible types.

**Comment by hajduakos** [comment]
8874404aadc8c8977c4c3fd73fd03309bb43e1d5 fixes it, but it is not yet merged

**Comment by dddejan** [comment]
What's the type of result when mixing memories?

**Comment by hajduakos** [comment]
The type of the conditional mixing `memory` and `storage` in these cases is `memory`

**Comment by hajduakos** [comment]
@dddejan #94 was merged, please check and close
